config/routes.rb
KernCoinProject::Application.routes.draw do



  root :to => redirect('/Home')

  match "error" => 'shortcut#error', :as => :error

  devise_for :admins, :skip => [:registrations]

  resources :elements, :only => [:destroy] do
    post :move_up, :on => :member
    post :move_down, :on => :member
  end


  # Questions for 'Contact Us'
  resources :questions, :only => [:new, :create]



  # Admin Namespace
  namespace "admin" do
    resources :dynamic_pages, :except => [:show]
    resources :menus, :only => [:index] do
      post :sort, :on => :collection
    end
    resources :items do
      post :reset_filters, :on => :collection
    end
    resources :blogs, :except => [:show] do
      resources :posts, :except => [:index]
    end
    resources :categories, :except => [:show] do
      post :move_up, :on => :member
      post :move_down, :on => :member
    end
    resources :questions, :only => [:index, :show, :destroy]
    resources :calendars, :except => [:show] do
      resources :events, :except => [:index]
    end
    scope :module => 'page_elems' do
      resources :login_elems, :only => [:new]
      resources :item_elems, :except => [:index, :show]
      resources :item_list_elems, :except => [:index, :show]
      resources :blog_elems, :except => [:index, :show]
      resources :calendar_elems, :except => [:index, :show]
      resources :text_elems, :except => [:index, :show]
      resources :link_list_elems, :except => [:index] do
        post :send_link_file, :on => :member
      end
    end
  end



  match ':shortcut(/:year(/:month))' => 'shortcut#route', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match 'Inventory/item_list' => 'inventory#list', :as => :inventory_list

#  match '/admin/:controller/:action(/:id)'
  match ':shortcut' => 'shortcut#route', :as => :shortcut
  match ':shortcut/:page_area/new_element' => 'dynamic_pages#new_element', :as => :new_element
#  match '/:controller/:action(/:kind)', :constraints => {:controller => 'ckeditor'} # Ckeditor file browsing
#  match '/*anything' => 'shortcut#error'


end

app/models/element.rb
#require  ActiveSupport::CoreExtensions::String
class Element < ActiveRecord::Base
  belongs_to :dynamic_page
  belongs_to :elem, :polymorphic => true

  acts_as_list :scope => :dynamic_page_id

  ELEM_TYPES = [
    ["Text"             ,   "text_elems"            ],
    ["Link List"        ,   "link_list_elems"       ],
    ["Item"             ,   "item_elems"            ],
    ["Item List"        ,   "item_list_elems"       ],
    #    ["Inventory Search" ,   "inventory_search_elems"],
    #    ["Recent News"      ,   "recent_news_elems"     ],
    ["Login"            ,   "login_elems"           ],
    ["Blog"             ,   "blog_elems"            ],
    ["Calendar"         ,   "calendar_elems"        ],
    #    ["Photo Gallery"    ,   "photo_gallery_elems"   ]
  ]


  before_validation :create_html_id
#  validates_numericality_of :position
  validates_numericality_of :page_area


  # Scopes

  # Returns the elements ordered from highest (first) to lowest (last)
  scope :elem_order, order('position asc')
  # Returns all Elements with the position passed in
  scope :page_area_elems, lambda {|page_area|
    where(:page_area => page_area)
  }
  # Returns the ordered elements for the passed in position
  scope :elements_for_page_area, lambda {|page_area|
    page_area_elems(page_area).elem_order
  }
  # Returns the next highest available column_order number for the passed in position
#  def self.set_highest_column_order(position)
#    col_order = 1 + Element.position_elems(position).maximum("column_order")
#    col_order
#  end


  def create_html_id
    self.html_id = self.title.empty? ? "element-#{self.id}" : self.title.downcase.parameterize.html_safe
  end

  # Select array
  def self.get_elem_select
    ELEM_TYPES
  end

  # Returns the string name of the elem controller
  def get_elem_controller
    elem_type.tableize
  end

  
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_filter :check_admin
  before_filter :get_node
  
  def destroy
    @current_element.destroy
    redirect_to( shortcut_path(@node.shortcut), :notice => 'Element successfully Destroyed')
  end

  def move_up
    @element = Element.find(params[:id])
    @element.move_higher
    redirect_to( shortcut_path(@node.shortcut), :notice => 'Element successfully Moved')
  end

  def move_down
    @element = Element.find(params[:id])
    @element.move_lower
    redirect_to( shortcut_path(@node.shortcut), :notice => 'Element successfully Moved')
  end


  private
  def get_node
    if params[:id]
      @current_element = Element.find(params[:id])
      @node = @current_element.dynamic_page.node
    end
    super
  end

end

app/views/elements/_element.html.erb
<!-- Element -->
<article  class="<%= element.elem_type %>">

  
  <% if element.elem_id %>
    <%= render :partial => "elem_partials/#{(element.elem_type.tableize).singularize}", :locals => {:elem => element.elem} %>
  <% else %>
    <%= render :partial => "elem_partials/#{(element.elem_type.tableize).singularize}", :locals => {:element => element} %>
  <% end %>

</article>
<!-- Element -->

app/views/elements/_element_controls.html.erb
<%= link_to image_tag("down.png", :alt => raw('&darr;')), move_down_element_path(element), :title => 'Move element down', :class => 'control', :method => :post %>
<%= link_to image_tag("up.png", :alt => raw('&uarr;')), move_up_element_path(element), :title => 'Move element up', :class => 'control', :method => :post %>

app/views/elements/_new_element_select.html.erb
<!-- Element -->
<article class="admin">
  <span class="controls">

    <%= form_tag(new_element_path(:shortcut => @shortcut, :page_area => page_area)) do %>
      <%= select_tag :elem_controller, options_for_select(Element.get_elem_select), :prompt => true %>
      <%= submit_tag "Add Element", :class => 'btn add small' %>
    <% end %>

  </span>
</article>
<!-- Element -->

app/views/elements/_page_area_elements.html.erb
<% if admin? %> <div class="admin clearfix"> <% end %>
  
  <% @elements.elements_for_page_area(page_area).each do |element|  %>
    <%= render :partial => 'elements/element', :locals => {:element => element} %>
  <% end %>

  <% if admin? %>
    <%= render :partial => 'elements/new_element_select', :locals => {:page_area => page_area} %>
  <% end %>

<% if admin? %> </div><% end %>

app/views/elements/_position_elements.html.erb
<% if admin? %> <div class="admin clearfix"> <% end %>
  
  <% @elements.elements_for_position(position).each do |element|  %>
    <%= render :partial => 'elements/element', :locals => {:element => element} %>
  <% end %>

  <% if admin? %>
    <%= render :partial => 'elements/new_element_select', :locals => {:position => position} %>
  <% end %>

<% if admin? %> </div><% end %>