config/routes.rb
KernCoinProject::Application.routes.draw do



  root :to => redirect('/Home')

  match "error" => 'shortcut#error', :as => :error

  devise_for :admins, :skip => [:registrations]

  resources :elements, :only => [:destroy] do
    post :move_up, :on => :member
    post :move_down, :on => :member
  end


  # Questions for 'Contact Us'
  resources :questions, :only => [:new, :create]



  # Admin Namespace
  namespace "admin" do
    resources :dynamic_pages, :except => [:show]
    resources :menus, :only => [:index] do
      post :sort, :on => :collection
    end
    resources :items do
      post :reset_filters, :on => :collection
    end
    resources :blogs, :except => [:show] do
      resources :posts, :except => [:index]
    end
    resources :categories, :except => [:show] do
      post :move_up, :on => :member
      post :move_down, :on => :member
    end
    resources :questions, :only => [:index, :show, :destroy]
    resources :calendars, :except => [:show] do
      resources :events, :except => [:index]
    end
    scope :module => 'page_elems' do
      resources :login_elems, :only => [:new]
      resources :item_elems, :except => [:index, :show]
      resources :item_list_elems, :except => [:index, :show]
      resources :blog_elems, :except => [:index, :show]
      resources :calendar_elems, :except => [:index, :show]
      resources :text_elems, :except => [:index, :show]
      resources :link_list_elems, :except => [:index] do
        post :send_link_file, :on => :member
      end
    end
  end



  match ':shortcut(/:year(/:month))' => 'shortcut#route', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match 'Inventory/item_list' => 'inventory#list', :as => :inventory_list

#  match '/admin/:controller/:action(/:id)'
  match ':shortcut' => 'shortcut#route', :as => :shortcut
  match ':shortcut/:page_area/new_element' => 'dynamic_pages#new_element', :as => :new_element
#  match '/:controller/:action(/:kind)', :constraints => {:controller => 'ckeditor'} # Ckeditor file browsing
#  match '/*anything' => 'shortcut#error'


end

app/views/elem_partials/_blog_elem.html.erb
<% if admin? %>
  <span class="controls">
    <% if elem.blog %>
      <%= link_to 'Add Post', new_admin_blog_post_path(elem.blog), :class => 'btn small' %>
      <%= link_to 'Manage Posts', shortcut_path(elem.blog.node.shortcut), :class => 'btn small' %>
    <% end %>
    <%= link_to 'Settings', edit_admin_blog_elem_path(elem), :class => 'btn small' %>
    <%= link_to image_tag("delete.png", :alt => 'X'), admin_blog_elem_path(elem) , :confirm => "Are you sure you wish to delete this element?", :method => :delete, :class => 'control' %>
    <%= render :partial => 'elements/element_controls', :locals => {:element => elem.element} %>
  </span>
<% end %>

<% if elem.blog %>
  <%
  blog = elem.blog
  other_blogs = elem.blogs
  posts = Post.order("post_date DESC").where('post_date <= ?', Time.now)
  posts = posts.limit(elem.count_limit) unless elem.count_limit.blank?
  posts = posts.where("posts.post_date >= ?", elem.past_limit) unless elem.past_limit.blank?
  posts = posts.where("posts.blog_id IN (?)", [blog.id] + other_blogs.collect {|b| b.id })
%>


  <% if elem.element.display_title %>
    <h1 class="title <%= elem.element.html_id %>"><%= elem.element.title %></h1>
    <a class="rss" href="/feed">Subscribe</a>
  <% end %>

  <% if posts[0] %>
    <%= render :partial => "elem_partials/blog_elem_partials/#{elem.display_type_partial}", :locals => {:blog => blog, :posts => posts} %>
  <% else %>
    <p>Right now, you do not have any blog posts displayed.
      Click &#8220;New Post&#8221; on the menu above or click &#8220;Settings&#8221; to import posts or change how the blog is displayed.</p>
    <p><em><strong>Hint:</strong> You can create an archive list of older posts organized by month and year simply by adding a blog element and choosing the &#8220;Archive&#8221; skin from the blog settings.</em></p>
  <% end %>
<% elsif admin? %>
  <h2>Blog Not Found</h2>
  <p>The blog this element was pulling from no longer exists.
    Please check your settings or delete this element.
  </p>
<% end %>

app/views/elem_partials/_calendar_elem.html.erb
<% if admin? %>
  <span class="controls">
    <%= link_to 'Add Event', new_admin_calendar_event_path(elem.calendar), :class => 'btn small' %>
    <%#= link_to 'Manage Events', shortcut_path(elem.calendar.node.shortcut), :class => 'btn small' %>
    <%= link_to 'Settings', edit_admin_calendar_elem_path(elem), :class => 'btn small' %>
    <%= link_to image_tag("delete.png", :alt => 'X'), admin_calendar_elem_path(elem), :confirm => "Are you sure you wish to delete this element?", :method => :delete, :class => 'control' %>
    <%= render :partial => 'elements/element_controls', :locals => {:element => elem.element} %>
  </span>
<% end %>

<%
calendar = elem.calendar
events = calendar.events
if (elem.display_type_partial == "event_list")
   events = events.limit(elem.max_events_shown) unless elem.max_events_shown.nil?
   events = events.where("events.start_at >= ?", elem.max_days_in_past.days) unless elem.max_days_in_past.nil?
   events = events.where("events.end_at >= ?", elem.max_days_in_future.days) unless elem.max_days_in_future.nil?
end
%>


<% if elem.element.display_title %><h1 class="title  <%= elem.element.html_id %> "><%= elem.element.title %></h1><% end %>
<%= render :partial => "elem_partials/calendar_elem_partials/#{elem.display_type_partial}", :locals => {:calendar => calendar, :events => events} %>

app/views/elem_partials/_category_list_elem.html.erb
<article class="category">
  <h1 class="title">Select a category to see further information and sub-categories within that region...</h1>
  <ul class="categoryList">
    <% Category.get_inventory.node.children.categories.each do |child| %>
      <li><%= link_to child.page.title, shortcut_path(child.shortcut) %></li>
    <% end %>
  </ul>
</article>

app/views/elem_partials/_item_elem.html.erb
<% if admin? %>
  <span class="controls">
    <%= link_to 'Edit Item', edit_admin_item_path(elem.item), :class => 'btn small' %>
    <%= link_to 'Settings', edit_admin_item_elem_path(elem), :class => 'btn small' %>
    <%= link_to image_tag("delete.png", :alt => 'X'), admin_item_elem_path(elem) , :confirm => "Are you sure?", :method => :delete, :class => 'control' %>
    <%= render :partial => 'elements/element_controls', :locals => {:element => elem.element} %>
  </span>
<% end %>

<% item = elem.item %>


<% if elem.element.display_title %><h1 class="title  <%= elem.element.html_id %> "><%= elem.element.title %></h1><% end %>

<%= render :partial => "elem_partials/item_elem_partials/#{elem.display_type_partial}", :locals => {:item => item} %>

app/views/elem_partials/_item_list_elem.html.erb
<% if admin? %>
  <span class="controls">
    <%= link_to 'Settings', edit_admin_item_list_elem_path(elem), :class => 'btn small' %>
    <%= link_to image_tag("delete.png", :alt => 'X'), admin_item_list_elem_path(elem) , :confirm => "Are you sure you wish to delete this element?", :method => :delete, :class => 'control' %>
    <%= render :partial => 'elements/element_controls', :locals => {:element => elem.element} %>
  </span>
<% end %>

<%
items = Item.scoped
items = items.limit(elem.limit) unless elem.limit.blank?
items = items.where("cost <= ?", elem.max_price) if elem.max_price_exists?
items = items.where("cost >= ?", elem.min_price) if elem.min_price_exists?
items = (elem.category ? items.to_a & elem.category.items : items.to_a)
%>


<% if elem.element.display_title %><h1 class="title  <%= elem.element.html_id %> "><%= elem.element.title %></h1><% end %>

<%= render :partial => "elem_partials/item_list_elem_partials/#{elem.display_type_partial}", :locals => {:items => items} %>

app/views/elem_partials/_link.html.erb
<% if link.link_type == "Url" %>
  <%= link_to (link.is_image ? image_tag(link.img_src, :alt => link.link_name, :style => link.image_style) : link.link_name), link.link_url, :target => link.target %>
<% end %>
<% if link.link_type == "Page" %>
  <%= link_to (link.is_image ? image_tag(link.img_src, :alt => link.link_name, :style => link.image_style) : link.link_name), link.node.url, :target => link.target %>
<% end %>
<% if link.link_type == "File" %>
  <%= link_to (link.is_image ? image_tag(link.img_src, :alt => link.link_name, :style => link.image_style) : link.link_name), send_link_file_admin_link_list_elem_path(link.link_list_elem, :link_id => link), :method => :post, :target => link.target %>
<% end %>

app/views/elem_partials/_link_list_elem.html.erb
<% if admin? %>
  <span class="controls">
    <%= link_to 'Edit', edit_admin_link_list_elem_path(elem), :class => 'btn small' %>
    <%= link_to image_tag("delete.png", :alt => 'X'), admin_link_list_elem_path(elem) , :confirm => "Are you sure you wish to delete this element?", :method => :delete, :class => 'control' %>
    <%= render :partial => 'elements/element_controls', :locals => {:element => elem.element} %>
  </span>
<% end %>

<% if elem.element.display_title %><h1 class="title  <%= elem.element.html_id %> "><%= elem.element.title %></h1><% end %>

<ul class="link_list_elem">
  <% elem.link_elems.each do |link| %>
    <%= content_tag_for :li, link do %>
      <%= render :partial => 'elem_partials/link', :locals => {:link => link} %>
    <% end %>
  <% end %>
</ul>

app/views/elem_partials/_login_elem.html.erb
<% if admin? %>
  <span class="controls">
    <%= link_to image_tag("delete.png", :alt => 'X'), element_path(element), :confirm => "Are you sure you wish to delete this element?", :method => :delete, :class => 'control' %>
    <%= render :partial => 'elements/element_controls', :locals => {:element => element} %>
  </span>
<% end %>

<% if element.display_title %><h1 class="title  <%= element.html_id %> "><%= element.title %></h1><% end %>

<% if admin_signed_in? %>
  <%= link_to "Logout", destroy_admin_session_path %>
<% else %>
  <div id="adminPage">
  <%= form_tag new_admin_session_path do %>
    <fieldset>
      <div class="field"><%= label_tag 'admin[email]', 'Email' %><%= text_field_tag 'admin[email]' %></div>
      <div class="field"><%= label_tag 'admin[password]', 'Password' %><%= password_field_tag 'admin[password]' %></div>
      <div class="field"><label>&nbsp;</label><%= submit_tag 'Login', :disable_with => '...Authenticating', :class => "btn medium" %> &nbsp;&nbsp;<%= link_to 'Sign Up', new_admin_registration_path() %></div>
    </fieldset>
  <% end %>
  </div>
<% end %>

app/views/elem_partials/_text_elem.html.erb
<% if admin? %>
  <span class="controls">
    <%= link_to 'Edit', edit_admin_text_elem_path(elem), :class => 'btn small' %>
    <%= link_to image_tag("delete.png", :alt => 'X'), admin_text_elem_path(elem) , :confirm => "Are you sure you wish to delete this element?", :method => :delete, :class => 'control' %>
    <%= render :partial => 'elements/element_controls', :locals => {:element => elem.element} %>
  </span>
<% end %>

<% if elem.element.display_title %><h1 class="title  <%= elem.element.html_id %> "><%= elem.element.title %></h1><% end %>    

<%=raw elem.text %>